# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint Checks Test

on:
  pull_request:
    branches:
      - 'aws/**'
  push:
    branches:
      '**/gh_actions_test'

jobs:
  lint-checks-test:
    runs-on: ubuntu-latest
    env:
      PYTHONWARNINGS: ignore
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Environment
        run: |
          ./devtool env_setup

      - name: Install dev dependencies with poetry
        run: |
          ./devtool install_deps_dev

      - name: Run pre-commit checks and lint
        run: |
          ./devtool lint
